<p class="large-text work-intro"><span class="red">Reverberation</span> documents the aural landscape of the city. It uses it to explore the impact of sound on its inhabitants and of the inhabitants on its soundscape.</p>

<div class="work-main wide">

<img src="work/images/reverberation_01.jpg" class="element"/>

<p class="text-three-column small-text">
<span class="red">Audio.</span><br/>
Using sounds sampled from multiple locations within a city, an audio landscape is created. Emphasizing specific frequencies in the sounds links them together and provides a narrative which reflects the variety encountered in a journey through the urban environment.
<br/><br>
<span class="red">Object.</span><br/>
These sounds are used to affect a multitude of similar objects. Using a custom built speaker to interface with a series of spheres, Reverberation creates hundered of interactions between individual elements and the soundscape of the city. The patterns that can be seen emerging are an emergent  result of the system set up and the audio generated by the spheres in motion adds a layer to the city experience as humans do to their habitat.</p>

<p class="text-three-column small-text last">
<span class="red">Installation.</span><br/>
The proposed expansion of Reverberation involves multiple speakers arranged to reflect the topography of a given city, pulling in live audio from the locations they represent.
<br/><br>
Allowing the viewer to walk around the pieces will provide a multi dimensional audio experience, shifting and changing based on position. The addition of further objects should create an overwhelming piece of sound, approaching white noise. The changes this would undergo over time with variations in the soundscapes of different parts of the city would produce a sense of time, scale and location within a limited area.</p>

</div>

<iframe class="element" src="http://player.vimeo.com/video/34376357?title=0&amp;byline=0&amp;portrait=0&amp;color=F0F7F5" width="660" height="371" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>